name: CI

on:
  push: # run on every push to main or any release branch
    branches: [main]
  pull_request: # and for every PR targeting main
    branches: [main]

jobs:
  # 1️⃣ Lint
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  # 2️⃣ Test (in parallel on 18, 20 & 22)
  test:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run test
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage

  # 3️⃣ Build & publish artifacts
  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # 4️⃣ Publish to npm (manual)
  publish:
    if: github.event_name == 'workflow_dispatch' # only on manual trigger
    runs-on: ubuntu-latest
    needs: build
    environment: npm
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: publish # guarantees one publish at a time
      cancel-in-progress: false

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish dist --access public --tag ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
